import { DEFAULT_SETTINGS } from "./extras";
import type { LepdoData, Transaction } from "./types";

function tx(t: Partial<Transaction> & Pick<Transaction, "id" | "code" | "date" | "sourceType" | "accountId" | "direction" | "amount" | "particulars">): Transaction {
  return {
    category: null,
    partyId: null,
    reconciled: false,
    voided: false,
    createdAt: `${t.date}T10:00:00.000Z`,
    updatedAt: `${t.date}T10:00:00.000Z`,
    createdBy: "Demo",
    ...t,
  } as Transaction;
}

export function buildSeed(): LepdoData {
  return {
    bankAccounts: [
      {
        id: "bank_hdfc",
        bankName: "LEPDO HDFC",
        nickname: "LEPDO HDFC",
        last4: "4821",
        openingBalance: 500000,
        active: true,
      },
      {
        id: "bank_indusind",
        bankName: "LEPDO IndusInd",
        nickname: "LEPDO IndusInd",
        last4: "7714",
        openingBalance: 220000,
        active: true,
      },
      {
        id: "bank_kotak",
        bankName: "Renuka Kotak",
        nickname: "Renuka Kotak",
        last4: "3390",
        openingBalance: 90000,
        active: true,
      },
      {
        id: "bank_sbi",
        bankName: "Brijes SBI",
        nickname: "Brijes SBI",
        last4: "9037",
        openingBalance: 150000,
        active: true,
      },
    ],
    cashLocations: [
      { id: "cash_itpark", name: "IT Park Cash", openingBalance: 40000, active: true },
      { id: "cash_mahidharpura", name: "Mahidharpura Cash", openingBalance: 25000, active: true },
    ],
    parties: [
      { id: "p_rajesh", name: "Rajesh Gems (Demo)", type: "customer" },
      { id: "p_shreeji", name: "Shreeji Exports (Demo)", type: "customer" },
      { id: "p_kiran", name: "Kiran Diamond Supply (Demo)", type: "supplier" },
      { id: "p_founder", name: "Founder — Owner Account (Demo)", type: "founder" },
      { id: "p_mehul", name: "Mehul Bhai (Demo)", type: "other" },
      { id: "p_office", name: "Office / Utilities (Demo)", type: "other" },
    ],
    salesInvoices: [
      { id: "si_1", number: "SI-2026-001", partyId: "p_rajesh", date: "2026-08-04", dueDate: "2026-08-19", total: 250000, paid: 250000 },
      { id: "si_2", number: "SI-2026-002", partyId: "p_shreeji", date: "2026-08-10", dueDate: "2026-08-25", total: 180000, paid: 80000 },
      { id: "si_3", number: "SI-2026-003", partyId: "p_rajesh", date: "2026-08-22", dueDate: "2026-09-06", total: 120000, paid: 0 },
    ],
    purchaseBills: [
      { id: "pb_1", number: "PB-2026-014", partyId: "p_kiran", date: "2026-08-06", total: 140000, paid: 90000 },
      { id: "pb_2", number: "PB-2026-018", partyId: "p_kiran", date: "2026-08-18", total: 60000, paid: 0 },
    ],
    transactions: [
      tx({
        id: "t1",
        code: "TXN-1001",
        date: "2026-08-05",
        sourceType: "bank",
        accountId: "bank_hdfc",
        direction: "in",
        amount: 250000,
        category: "sale_payment",
        partyId: "p_rajesh",
        particulars: "Full payment received against SI-2026-001 (Demo)",
        reference: "UTR8891204",
        allocations: [{ invoiceId: "si_1", amount: 250000 }],
        reconciled: true,
      }),
      tx({
        id: "t2",
        code: "TXN-1002",
        date: "2026-08-11",
        sourceType: "bank",
        accountId: "bank_hdfc",
        direction: "in",
        amount: 80000,
        category: "sale_payment",
        partyId: "p_shreeji",
        particulars: "Part payment against SI-2026-002 (Demo)",
        reference: "UTR8891555",
        allocations: [{ invoiceId: "si_2", amount: 80000 }],
      }),
      tx({
        id: "t3",
        code: "TXN-1003",
        date: "2026-08-14",
        sourceType: "bank",
        accountId: "bank_sbi",
        direction: "in",
        amount: 50000,
        category: "sale_payment",
        partyId: "p_rajesh",
        particulars: "Advance received, no invoice yet — customer advance (Demo)",
        reference: "UTR8891900",
        allocations: [],
        advanceAmount: 50000,
      }),
      tx({
        id: "t4",
        code: "TXN-1004",
        date: "2026-08-16",
        sourceType: "bank",
        accountId: "bank_hdfc",
        direction: "out",
        amount: 18500,
        category: "expense",
        partyId: "p_office",
        particulars: "Office electricity and internet bill (Demo)",
        reference: "BILL-AUG-26",
      }),
      tx({
        id: "t5",
        code: "TXN-1005",
        date: "2026-08-19",
        sourceType: "bank",
        accountId: "bank_hdfc",
        direction: "out",
        amount: 90000,
        category: "purchase_payment",
        partyId: "p_kiran",
        particulars: "Part payment against PB-2026-014 (Demo)",
        reference: "UTR8892210",
        allocations: [{ invoiceId: "pb_1", amount: 90000 }],
      }),
      tx({
        id: "t6",
        code: "TXN-1006",
        date: "2026-08-20",
        sourceType: "cash",
        accountId: "cash_mahidharpura",
        direction: "out",
        amount: 15000,
        category: "uchhina_money_given",
        partyId: "p_mehul",
        particulars: "Uchhina given to Mehul Bhai (Demo)",
        uchhinaReturnDate: "2026-09-20",
      }),
      tx({
        id: "t7a",
        code: "TXN-1007",
        date: "2026-08-24",
        sourceType: "bank",
        accountId: "bank_hdfc",
        direction: "out",
        amount: 100000,
        category: "bank_transfer",
        partyId: null,
        particulars: "Transfer to State Bank of India — LEPDO Savings (Demo)",
        reference: "TRF-5001",
        transferGroupId: "trf_5001",
      }),
      tx({
        id: "t7b",
        code: "TXN-1008",
        date: "2026-08-24",
        sourceType: "bank",
        accountId: "bank_sbi",
        direction: "in",
        amount: 100000,
        category: "bank_transfer",
        partyId: null,
        particulars: "Transfer from HDFC Bank — LEPDO Current (Demo)",
        reference: "TRF-5001",
        transferGroupId: "trf_5001",
      }),
      tx({
        id: "t8a",
        code: "TXN-1009",
        date: "2026-08-26",
        sourceType: "bank",
        accountId: "bank_hdfc",
        direction: "out",
        amount: 60000,
        category: "bank_to_cash",
        partyId: null,
        particulars: "Cash withdrawal for IT Park office (Demo)",
        reference: "TRF-5002",
        transferGroupId: "trf_5002",
      }),
      tx({
        id: "t8b",
        code: "TXN-1010",
        date: "2026-08-26",
        sourceType: "cash",
        accountId: "cash_itpark",
        direction: "in",
        amount: 60000,
        category: "bank_to_cash",
        partyId: null,
        particulars: "Cash received from HDFC Bank withdrawal (Demo)",
        reference: "TRF-5002",
        transferGroupId: "trf_5002",
      }),
      tx({
        id: "t9",
        code: "TXN-1011",
        date: "2026-08-27",
        sourceType: "cash",
        accountId: "cash_itpark",
        direction: "out",
        amount: 4200,
        category: null,
        partyId: null,
        particulars: "Imported statement line pending review (Demo)",
      }),
    ],
    auditLogs: [
      {
        id: "a1",
        at: "2026-08-27T10:00:00.000Z",
        action: "seed",
        entity: "workspace",
        detail: "Demo data loaded for Phase 1 walkthrough",
        by: "System",
      },
    ],
    brokers: [],
    sellers: [],
    liabilities: [],
    liabilityEntries: [],
    stockEntries: [],
    teamMembers: [],
    teamPayments: [],
    goals: [],
    settings: DEFAULT_SETTINGS,
  };
}
