/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BankLedgerRouteImport } from './routes/bank-ledger'
import { Route as CapitalRouteImport } from './routes/capital'
import { Route as CashBookRouteImport } from './routes/cash-book'
import { Route as DrawingsRouteImport } from './routes/drawings'
import { Route as ExpenseRouteImport } from './routes/expense'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as PlRouteImport } from './routes/pl'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StockRouteImport } from './routes/stock'
import { Route as TeamRouteImport } from './routes/team'
import { Route as UchhinaRouteImport } from './routes/uchhina'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankLedgerRoute = BankLedgerRouteImport.update({
  id: '/bank-ledger',
  path: '/bank-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const CapitalRoute = CapitalRouteImport.update({
  id: '/capital',
  path: '/capital',
  getParentRoute: () => rootRouteImport,
} as any)
const CashBookRoute = CashBookRouteImport.update({
  id: '/cash-book',
  path: '/cash-book',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsRoute = DrawingsRouteImport.update({
  id: '/drawings',
  path: '/drawings',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseRoute = ExpenseRouteImport.update({
  id: '/expense',
  path: '/expense',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const PlRoute = PlRouteImport.update({
  id: '/pl',
  path: '/pl',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const UchhinaRoute = UchhinaRouteImport.update({
  id: '/uchhina',
  path: '/uchhina',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bank-ledger': typeof BankLedgerRoute
  '/capital': typeof CapitalRoute
  '/cash-book': typeof CashBookRoute
  '/drawings': typeof DrawingsRoute
  '/expense': typeof ExpenseRoute
  '/goals': typeof GoalsRoute
  '/pl': typeof PlRoute
  '/purchase': typeof PurchaseRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/team': typeof TeamRoute
  '/uchhina': typeof UchhinaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bank-ledger': typeof BankLedgerRoute
  '/capital': typeof CapitalRoute
  '/cash-book': typeof CashBookRoute
  '/drawings': typeof DrawingsRoute
  '/expense': typeof ExpenseRoute
  '/goals': typeof GoalsRoute
  '/pl': typeof PlRoute
  '/purchase': typeof PurchaseRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/team': typeof TeamRoute
  '/uchhina': typeof UchhinaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bank-ledger': typeof BankLedgerRoute
  '/capital': typeof CapitalRoute
  '/cash-book': typeof CashBookRoute
  '/drawings': typeof DrawingsRoute
  '/expense': typeof ExpenseRoute
  '/goals': typeof GoalsRoute
  '/pl': typeof PlRoute
  '/purchase': typeof PurchaseRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/team': typeof TeamRoute
  '/uchhina': typeof UchhinaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bank-ledger'
    | '/capital'
    | '/cash-book'
    | '/drawings'
    | '/expense'
    | '/goals'
    | '/pl'
    | '/purchase'
    | '/reports'
    | '/reset-password'
    | '/sales'
    | '/settings'
    | '/stock'
    | '/team'
    | '/uchhina'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bank-ledger'
    | '/capital'
    | '/cash-book'
    | '/drawings'
    | '/expense'
    | '/goals'
    | '/pl'
    | '/purchase'
    | '/reports'
    | '/reset-password'
    | '/sales'
    | '/settings'
    | '/stock'
    | '/team'
    | '/uchhina'
  id:
    | '__root__'
    | '/'
    | '/bank-ledger'
    | '/capital'
    | '/cash-book'
    | '/drawings'
    | '/expense'
    | '/goals'
    | '/pl'
    | '/purchase'
    | '/reports'
    | '/reset-password'
    | '/sales'
    | '/settings'
    | '/stock'
    | '/team'
    | '/uchhina'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankLedgerRoute: typeof BankLedgerRoute
  CapitalRoute: typeof CapitalRoute
  CashBookRoute: typeof CashBookRoute
  DrawingsRoute: typeof DrawingsRoute
  ExpenseRoute: typeof ExpenseRoute
  GoalsRoute: typeof GoalsRoute
  PlRoute: typeof PlRoute
  PurchaseRoute: typeof PurchaseRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRoute
  StockRoute: typeof StockRoute
  TeamRoute: typeof TeamRoute
  UchhinaRoute: typeof UchhinaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-ledger': {
      id: '/bank-ledger'
      path: '/bank-ledger'
      fullPath: '/bank-ledger'
      preLoaderRoute: typeof BankLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capital': {
      id: '/capital'
      path: '/capital'
      fullPath: '/capital'
      preLoaderRoute: typeof CapitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-book': {
      id: '/cash-book'
      path: '/cash-book'
      fullPath: '/cash-book'
      preLoaderRoute: typeof CashBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings': {
      id: '/drawings'
      path: '/drawings'
      fullPath: '/drawings'
      preLoaderRoute: typeof DrawingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense': {
      id: '/expense'
      path: '/expense'
      fullPath: '/expense'
      preLoaderRoute: typeof ExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pl': {
      id: '/pl'
      path: '/pl'
      fullPath: '/pl'
      preLoaderRoute: typeof PlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uchhina': {
      id: '/uchhina'
      path: '/uchhina'
      fullPath: '/uchhina'
      preLoaderRoute: typeof UchhinaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankLedgerRoute: BankLedgerRoute,
  CapitalRoute: CapitalRoute,
  CashBookRoute: CashBookRoute,
  DrawingsRoute: DrawingsRoute,
  ExpenseRoute: ExpenseRoute,
  GoalsRoute: GoalsRoute,
  PlRoute: PlRoute,
  PurchaseRoute: PurchaseRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRoute,
  StockRoute: StockRoute,
  TeamRoute: TeamRoute,
  UchhinaRoute: UchhinaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
